/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../Factory/Factory';
import * as import4 from './home';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/platform/platform';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/components/popover/popover';
import * as import13 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import14 from 'ionic-angular/components/alert/alert';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from 'ionic-angular/components/button/button';
import * as import23 from 'ionic-angular/components/icon/icon';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from 'ionic-angular/components/segment/segment';
import * as import27 from 'ionic-angular/components/content/content';
import * as import28 from 'ionic-angular/components/fab/fab';
import * as import29 from '@angular/common/src/directives/ng_switch';
import * as import30 from '../../GroupBy/GroupBy';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import38 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import39 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import40 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import41 from 'ionic-angular/util/keyboard';
import * as import42 from '@angular/core/src/zone/ng_zone';
import * as import43 from 'ionic-angular/components/tabs/tabs';
import * as import44 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import45 from '@angular/core/src/linker/template_ref';
import * as import46 from '@angular/forms/src/directives/ng_control';
import * as import47 from 'ionic-angular/components/grid/grid';
import * as import48 from '@angular/common/src/directives/ng_for';
import * as import49 from '@angular/common/src/pipes/slice_pipe';
import * as import50 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import51 from 'ionic-angular/components/card/card';
import * as import52 from '@angular/core/src/security';
import * as import53 from 'ionic-angular/components/item/item';
import * as import54 from 'ionic-angular/components/list/list';
import * as import55 from 'ionic-angular/gestures/gesture-controller';
import * as import56 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import57 from 'ionic-angular/util/form';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Factory_0_4:import3.Factory;
  _HomePage_0_5:import4.HomePage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Factory_0_4 = new import3.Factory(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.Platform));
    this._HomePage_0_5 = new import4.HomePage(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.Platform),this.parentInjector.get(import11.NavController),this._Factory_0_4,this.parentInjector.get(import12.PopoverController),this.parentInjector.get(import13.ActionSheetController),this.parentInjector.get(import14.AlertController));
    this._appEl_0.initComponent(this._HomePage_0_5,[],compView_0);
    compView_0.create(this._HomePage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Factory) && (0 === requestNodeIndex))) { return this._Factory_0_4; }
    if (((token === import4.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import16.ComponentFactory<import4.HomePage> = new import16.ComponentFactory<import4.HomePage>('page-home',viewFactory_HomePage_Host0,import4.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import4.HomePage> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import19.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import20.ToolbarItem;
  _query_Button_7_0:import21.QueryList<any>;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Button_9_4:import22.Button;
  _el_10:any;
  _Icon_10_3:import23.Icon;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Button_12_4:import22.Button;
  _el_13:any;
  _Icon_13_3:import23.Icon;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Toolbar_17_4:import17.Toolbar;
  _text_18:any;
  _el_19:any;
  _NgModel_19_3:import24.NgModel;
  _NgControl_19_4:any;
  _NgControlStatus_19_5:import25.NgControlStatus;
  _Segment_19_6:import26.Segment;
  _query_SegmentButton_19_0:import21.QueryList<any>;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _SegmentButton_21_4:import26.SegmentButton;
  _text_22:any;
  _el_23:any;
  _Icon_23_3:import23.Icon;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _SegmentButton_26_4:import26.SegmentButton;
  _text_27:any;
  _el_28:any;
  _Icon_28_3:import23.Icon;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Content_34_4:import27.Content;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _FabContainer_37_4:import28.FabContainer;
  _query_FabButton_37_0:import21.QueryList<any>;
  _query_FabList_37_1:import21.QueryList<any>;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _FabButton_39_4:import28.FabButton;
  _el_40:any;
  _Icon_40_3:import23.Icon;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _NgSwitch_43_3:import29.NgSwitch;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import2.AppElement;
  _TemplateRef_45_5:any;
  _NgSwitchCase_45_6:import29.NgSwitchCase;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _TemplateRef_47_5:any;
  _NgSwitchCase_47_6:import29.NgSwitchCase;
  _text_48:any;
  _text_49:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  _pipe_groupBy_0:import30.GroupBy;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','primary');
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'no-border-bottom','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import34.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import36.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      Sports PIP\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import20.ToolbarItem(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_7_0 = new import21.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'icon-only','');
    this.renderer.setElementAttribute(this._el_9,'ion-button','');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import37.viewFactory_Button0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Button_9_4 = new import22.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_9),this.renderer);
    this._appEl_9.initComponent(this._Button_9_4,[],compView_9);
    this._el_10 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_10,'name','settings');
    this.renderer.setElementAttribute(this._el_10,'role','img');
    this._Icon_10_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_10),this.renderer);
    compView_9.create(this._Button_9_4,[[].concat([this._el_10])],(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'icon-only','');
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import2.AppElement(12,7,this,this._el_12);
    var compView_12:any = import37.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import22.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4,[],compView_12);
    this._el_13 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_13,'name','more');
    this.renderer.setElementAttribute(this._el_13,'role','img');
    this._Icon_13_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_13),this.renderer);
    compView_12.create(this._Button_12_4,[[].concat([this._el_13])],(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [].concat([this._el_7]),
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','toolbar');
    this.renderer.setElementAttribute(this._el_17,'no-border-top','');
    this._appEl_17 = new import2.AppElement(17,0,this,this._el_17);
    var compView_17:any = import38.viewFactory_Toolbar0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Toolbar_17_4 = new import17.Toolbar(this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Toolbar_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_19_3 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_19_4 = this._NgModel_19_3;
    this._NgControlStatus_19_5 = new import25.NgControlStatus(this._NgControl_19_4);
    this._Segment_19_6 = new import26.Segment(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_19),this.renderer,this._NgControl_19_4);
    this._query_SegmentButton_19_0 = new import21.QueryList<any>();
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','segment-button');
    this.renderer.setElementAttribute(this._el_21,'role','button');
    this.renderer.setElementAttribute(this._el_21,'tappable','');
    this.renderer.setElementAttribute(this._el_21,'value','local');
    this._appEl_21 = new import2.AppElement(21,19,this,this._el_21);
    var compView_21:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(21),this._appEl_21);
    this._SegmentButton_21_4 = new import26.SegmentButton(this.renderer,new import32.ElementRef(this._el_21));
    this._appEl_21.initComponent(this._SegmentButton_21_4,[],compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_23,'name','albums');
    this.renderer.setElementAttribute(this._el_23,'role','img');
    this._Icon_23_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_23),this.renderer);
    this._text_24 = this.renderer.createText((null as any),' Matrices\n      ',(null as any));
      compView_21.create(this._SegmentButton_21_4,[[].concat([
        this._text_22,
        this._el_23,
        this._text_24
      ]
    )],(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_19,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','segment-button');
    this.renderer.setElementAttribute(this._el_26,'role','button');
    this.renderer.setElementAttribute(this._el_26,'tappable','');
    this.renderer.setElementAttribute(this._el_26,'value','server');
    this._appEl_26 = new import2.AppElement(26,19,this,this._el_26);
    var compView_26:any = import39.viewFactory_SegmentButton0(this.viewUtils,this.injector(26),this._appEl_26);
    this._SegmentButton_26_4 = new import26.SegmentButton(this.renderer,new import32.ElementRef(this._el_26));
    this._appEl_26.initComponent(this._SegmentButton_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','cloud-download');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText((null as any),' Channels\n      ',(null as any));
      compView_26.create(this._SegmentButton_26_4,[[].concat([
        this._text_27,
        this._el_28,
        this._text_29
      ]
    )],(null as any));
    this._text_30 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_17.create(this._Toolbar_17_4,[
      [],
      [],
      [],
      [].concat([
        this._text_18,
        this._el_19,
        this._text_31
      ]
      )
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_34 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_34,'style','background:#f1f1f1;');
    this._appEl_34 = new import2.AppElement(34,(null as any),this,this._el_34);
    var compView_34:any = import40.viewFactory_Content0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Content_34_4 = new import27.Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import41.Keyboard),this.parentInjector.get(import42.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import43.Tabs,(null as any)));
    this._appEl_34.initComponent(this._Content_34_4,[],compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_37,'bottom','');
    this.renderer.setElementAttribute(this._el_37,'right','');
    this._appEl_37 = new import2.AppElement(37,34,this,this._el_37);
    var compView_37:any = import44.viewFactory_FabContainer0(this.viewUtils,this.injector(37),this._appEl_37);
    this._FabContainer_37_4 = new import28.FabContainer(new import32.ElementRef(this._el_37));
    this._query_FabButton_37_0 = new import21.QueryList<any>();
    this._query_FabList_37_1 = new import21.QueryList<any>();
    this._appEl_37.initComponent(this._FabContainer_37_4,[],compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'ion-fab','');
    this._appEl_39 = new import2.AppElement(39,37,this,this._el_39);
    var compView_39:any = import44.viewFactory_FabButton0(this.viewUtils,this.injector(39),this._appEl_39);
    this._FabButton_39_4 = new import28.FabButton(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_39),this.renderer);
    this._appEl_39.initComponent(this._FabButton_39_4,[],compView_39);
    this._el_40 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'name','add');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_40),this.renderer);
    compView_39.create(this._FabButton_39_4,[[].concat([this._el_40])],(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_FabButton_37_0.reset([this._FabButton_39_4]);
    this._FabContainer_37_4._mainButton = this._query_FabButton_37_0.first;
      compView_37.create(this._FabContainer_37_4,[[].concat([
        this._text_38,
        this._el_39,
        this._text_41
      ]
    )],(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'div',(null as any));
    this._NgSwitch_43_3 = new import29.NgSwitch();
    this._text_44 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._anchor_45 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._appEl_45 = new import2.AppElement(45,43,this,this._anchor_45);
    this._TemplateRef_45_5 = new import45.TemplateRef_(this._appEl_45,viewFactory_HomePage1);
    this._NgSwitchCase_45_6 = new import29.NgSwitchCase(this._appEl_45.vcRef,this._TemplateRef_45_5,this._NgSwitch_43_3);
    this._text_46 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._appEl_47 = new import2.AppElement(47,43,this,this._anchor_47);
    this._TemplateRef_47_5 = new import45.TemplateRef_(this._appEl_47,viewFactory_HomePage3);
    this._NgSwitchCase_47_6 = new import29.NgSwitchCase(this._appEl_47.vcRef,this._TemplateRef_47_5,this._NgSwitch_43_3);
    this._text_48 = this.renderer.createText(this._el_43,'\n  ',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_34.create(this._Content_34_4,[
      [].concat([this._el_37]),
      [].concat([
        this._text_35,
        this._text_36,
        this._text_42,
        this._el_43,
        this._text_49
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_19,'ngModelChange',this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_10 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_19_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_25 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_27 = import8.UNINITIALIZED;
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._pipe_groupBy_0 = new import30.GroupBy();
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._text_49
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import23.Icon) && (10 === requestNodeIndex))) { return this._Icon_10_3; }
    if (((token === import22.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_9_4; }
    if (((token === import23.Icon) && (13 === requestNodeIndex))) { return this._Icon_13_3; }
    if (((token === import22.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_12_4; }
    if (((token === import20.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarItem_7_3; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_2_4; }
    if (((token === import23.Icon) && (23 === requestNodeIndex))) { return this._Icon_23_3; }
    if (((token === import26.SegmentButton) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._SegmentButton_21_4; }
    if (((token === import23.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3; }
    if (((token === import26.SegmentButton) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._SegmentButton_26_4; }
    if (((token === import24.NgModel) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgModel_19_3; }
    if (((token === import46.NgControl) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControl_19_4; }
    if (((token === import25.NgControlStatus) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControlStatus_19_5; }
    if (((token === import26.Segment) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Segment_19_6; }
    if (((token === import17.Toolbar) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Toolbar_17_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Header_0_3; }
    if (((token === import23.Icon) && (40 === requestNodeIndex))) { return this._Icon_40_3; }
    if (((token === import28.FabButton) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._FabButton_39_4; }
    if (((token === import28.FabContainer) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._FabContainer_37_4; }
    if (((token === import45.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import29.NgSwitchCase) && (45 === requestNodeIndex))) { return this._NgSwitchCase_45_6; }
    if (((token === import45.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import29.NgSwitchCase) && (47 === requestNodeIndex))) { return this._NgSwitchCase_47_6; }
    if (((token === import29.NgSwitch) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgSwitch_43_3; }
    if (((token === import27.Content) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Content_34_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const currVal_3:any = 'settings';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_10_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = 'more';
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_13_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    changes = (null as any);
    const currVal_10:any = this.context.selectedSegment;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgModel_19_3.model = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgModel_19_3.ngOnChanges(changes); }
    const currVal_18:any = 'local';
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._SegmentButton_21_4.value = currVal_18;
      this._expr_18 = currVal_18;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_21_4.ngOnInit(); }
    const currVal_19:any = 'albums';
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Icon_23_3.name = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_22:any = 'server';
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._SegmentButton_26_4.value = currVal_22;
      this._expr_22 = currVal_22;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_26_4.ngOnInit(); }
    const currVal_23:any = 'cloud-download';
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._Icon_28_3.name = currVal_23;
      this._expr_23 = currVal_23;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_34_4.ngOnInit(); }
    const currVal_27:any = 'add';
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._Icon_40_3.name = currVal_27;
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = this.context.selectedSegment;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._NgSwitch_43_3.ngSwitch = currVal_29;
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = 'local';
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._NgSwitchCase_45_6.ngSwitchCase = currVal_30;
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = 'server';
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgSwitchCase_47_6.ngSwitchCase = currVal_31;
      this._expr_31 = currVal_31;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([
          this._Button_9_4,
          this._Button_12_4
        ]
        );
        this._ToolbarItem_7_3._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_19_0.dirty) {
        this._query_SegmentButton_19_0.reset([
          this._SegmentButton_21_4,
          this._SegmentButton_26_4
        ]
        );
        this._Segment_19_6._buttons = this._query_SegmentButton_19_0;
        this._query_SegmentButton_19_0.notifyOnChanges();
      }
      if (this._query_FabList_37_1.dirty) {
        this._query_FabList_37_1.reset([]);
        this._FabContainer_37_4._fabLists = this._query_FabList_37_1;
        this._query_FabList_37_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_37_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._Icon_10_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_10,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._Icon_13_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_13,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Toolbar_17_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatus_19_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_19_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_19_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_19_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_19_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_19_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_20:any = this._Icon_23_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_23,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_24:any = this._Icon_28_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._Content_34_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_34,'statusbar-padding',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = this._Icon_40_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_19_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_10_3.ngOnDestroy();
    this._Icon_13_3.ngOnDestroy();
    this._Icon_23_3.ngOnDestroy();
    this._Icon_28_3.ngOnDestroy();
    this._NgModel_19_3.ngOnDestroy();
    this._Icon_40_3.ngOnDestroy();
    this._FabContainer_37_4.ngOnDestroy();
    this._Content_34_4.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.openSettings()) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.presentPopover($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selectedSegment = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this._appEl_21.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_21_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this._appEl_26.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_26_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.newMatrix()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('d:/git/sportspip/.tmp/pages/home/home.html',0,import15.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import47.Row;
  _text_3:any;
  _el_4:any;
  _Col_4_3:import47.Col;
  _text_5:any;
  _el_6:any;
  _Col_6_3:import47.Col;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _Button_8_4:import22.Button;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import48.NgFor;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_1:any;
  _pipe_slice_0:import49.SlicePipe;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this._Row_2_3 = new import47.Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_4,'center','');
    this._Col_4_3 = new import47.Col();
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_6,'text-right','');
    this._Col_6_3 = new import47.Col();
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'clear','');
    this.renderer.setElementAttribute(this._el_8,'ion-button','');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import37.viewFactory_Button0(this.viewUtils,this.injector(8),this._appEl_8);
    this._Button_8_4 = new import22.Button((null as any),'',this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_8),this.renderer);
    this._appEl_8.initComponent(this._Button_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'View All',(null as any));
    compView_8.create(this._Button_8_4,[[].concat([this._text_9])],(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','items');
    this._text_14 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_15 = new import2.AppElement(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import45.TemplateRef_(this._appEl_15,viewFactory_HomePage2);
    this._NgFor_15_6 = new import48.NgFor(this._appEl_15.vcRef,this._TemplateRef_15_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_16 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._pipe_slice_0 = new import49.SlicePipe();
    this._expr_2 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import47.Col) && (4 === requestNodeIndex))) { return this._Col_4_3; }
    if (((token === import22.Button) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Button_8_4; }
    if (((token === import47.Col) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Col_6_3; }
    if (((token === import47.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Row_2_3; }
    if (((token === import45.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import48.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    changed = false;
    const currVal_1:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_8_4.clear = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_8.componentView.markAsCheckOnce(); }
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_2:any = valUnwrapper.unwrap(this._pipe_slice_0.transform(this.parent.context.localMatrices,0,12));
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this._NgFor_15_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_15_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_15_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_8_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openCollection()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import51.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _CardContent_6_3:import51.CardContent;
  _text_7:any;
  _el_8:any;
  _CardTitle_8_3:import51.CardTitle;
  _text_9:any;
  _el_10:any;
  _Row_10_3:import47.Row;
  _text_11:any;
  _el_12:any;
  _Col_12_3:import47.Col;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _Col_18_3:import47.Col;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage2,renderType_HomePage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item');
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_2_3 = new import51.Card(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'ion-card-content',(null as any));
    this._CardContent_6_3 = new import51.CardContent();
    this._text_7 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'ion-card-title',(null as any));
    this.renderer.setElementAttribute(this._el_8,'style','font-size:18px;flex-wrap: nowrap;');
    this._CardTitle_8_3 = new import51.CardTitle();
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'ion-row',(null as any));
    this._Row_10_3 = new import47.Row();
    this._text_11 = this.renderer.createText(this._el_10,'\n                  ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this._Col_12_3 = new import47.Col();
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'style','text-overflow:ellipsis;');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                  ',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n                  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_18,'center','');
    this.renderer.setElementAttribute(this._el_18,'style','width:10px;');
    this.renderer.setElementAttribute(this._el_18,'text-right','');
    this._Col_18_3 = new import47.Col();
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Oct 3',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                  ',(null as any));
    this._text_23 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_8,'\n              ',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'style','display:block;');
    this._text_27 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Sport/Skill',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'00:00',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n              ',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import47.Col) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Col_12_3; }
    if (((token === import47.Col) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Col_18_3; }
    if (((token === import47.Row) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Row_10_3; }
    if (((token === import51.CardTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._CardTitle_8_3; }
    if (((token === import51.CardContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._CardContent_6_3; }
    if (((token === import51.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Card_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.image;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import52.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import5.interpolate(1,'',this.context.$implicit.title,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_15,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.openMatrix(this.context.$implicit.title)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage2(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import48.NgFor;
  _text_3:any;
  _pipe_groupBy_0_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage3,renderType_HomePage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import45.TemplateRef_(this._appEl_2,viewFactory_HomePage4);
    this._NgFor_2_6 = new import48.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import50.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._pipe_groupBy_0_0 = import5.pureProxy2((<_View_HomePage0>this.parent)._pipe_groupBy_0.transform.bind((<_View_HomePage0>this.parent)._pipe_groupBy_0));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import48.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_0:any = valUnwrapper.unwrap(import5.castByValue(this._pipe_groupBy_0_0,(<_View_HomePage0>this.parent)._pipe_groupBy_0.transform)(this.parent.context.channels,'Channel'));
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage3(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage4 extends import1.AppView<any> {
  _el_0:any;
  _ItemGroup_0_3:import53.ItemGroup;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import47.Row;
  _text_3:any;
  _el_4:any;
  _Col_4_3:import47.Col;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ToolbarTitle_6_4:import19.ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _Col_10_3:import47.Col;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Button_12_4:import22.Button;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import48.NgFor;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  _pipe_slice_0:import49.SlicePipe;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage4,renderType_HomePage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_0_3 = new import53.ItemGroup();
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this._Row_2_3 = new import47.Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_4,'center','');
    this._Col_4_3 = new import47.Col();
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-title',(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import36.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import19.ToolbarTitle(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_6),this.renderer,this.parent.parent.parentInjector.get(import17.Toolbar,(null as any)),this.parent.parent.parentInjector.get(import18.Navbar,(null as any)));
    this._appEl_6.initComponent(this._ToolbarTitle_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'',(null as any));
    compView_6.create(this._ToolbarTitle_6_4,[[].concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_10,'text-right','');
    this._Col_10_3 = new import47.Col();
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'clear','');
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import2.AppElement(12,10,this,this._el_12);
    var compView_12:any = import37.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import22.Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'View All',(null as any));
    compView_12.create(this._Button_12_4,[[].concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','items');
    this._text_18 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._appEl_19 = new import2.AppElement(19,17,this,this._anchor_19);
    this._TemplateRef_19_5 = new import45.TemplateRef_(this._appEl_19,viewFactory_HomePage5);
    this._NgFor_19_6 = new import48.NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parent.parent.parentInjector.get(import50.IterableDiffers),this.parent.parent.ref);
    this._text_20 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    this._pipe_slice_0 = new import49.SlicePipe();
    this._expr_3 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4; }
    if (((token === import47.Col) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Col_4_3; }
    if (((token === import22.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_12_4; }
    if (((token === import47.Col) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Col_10_3; }
    if (((token === import47.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Row_2_3; }
    if (((token === import45.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import48.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6; }
    if (((token === import53.ItemGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemGroup_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    changed = false;
    const currVal_2:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_12_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_12.componentView.markAsCheckOnce(); }
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_3:any = valUnwrapper.unwrap(this._pipe_slice_0.transform(this.context.$implicit.value,0,6));
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this._NgFor_19_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_19_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_19_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterContentInit(); } }
    const currVal_0:any = import5.interpolate(1,'',this.context.$implicit.key,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.openChannelCollection(this.context.$implicit.Channel)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage4(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import51.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _CardContent_6_3:import51.CardContent;
  _text_7:any;
  _el_8:any;
  _CardTitle_8_3:import51.CardTitle;
  _text_9:any;
  _el_10:any;
  _Row_10_3:import47.Row;
  _text_11:any;
  _el_12:any;
  _Col_12_3:import47.Col;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _Col_18_3:import47.Col;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage5,renderType_HomePage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_2_3 = new import51.Card(this.parent.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n              ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','assets/sample.jpg');
    this._text_5 = this.renderer.createText(this._el_2,'\n              ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'ion-card-content',(null as any));
    this._CardContent_6_3 = new import51.CardContent();
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'ion-card-title',(null as any));
    this.renderer.setElementAttribute(this._el_8,'style','font-size:18px;flex-wrap: nowrap;');
    this._CardTitle_8_3 = new import51.CardTitle();
    this._text_9 = this.renderer.createText(this._el_8,'\n                  ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'ion-row',(null as any));
    this._Row_10_3 = new import47.Row();
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this._Col_12_3 = new import47.Col();
    this._text_13 = this.renderer.createText(this._el_12,'\n                      ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'style','text-overflow:ellipsis;');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_10,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_18,'center','');
    this.renderer.setElementAttribute(this._el_18,'style','width:10px;');
    this.renderer.setElementAttribute(this._el_18,'text-right','');
    this._Col_18_3 = new import47.Col();
    this._text_19 = this.renderer.createText(this._el_18,'\n                      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_10,'\n                  ',(null as any));
    this._text_24 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'style','display:block;');
    this._text_27 = this.renderer.createText(this._el_26,'\n                  ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n                  ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._text_35 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import47.Col) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Col_12_3; }
    if (((token === import47.Col) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Col_18_3; }
    if (((token === import47.Row) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Row_10_3; }
    if (((token === import51.CardTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._CardTitle_8_3; }
    if (((token === import51.CardContent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._CardContent_6_3; }
    if (((token === import51.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Card_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import5.interpolate(1,'',this.context.$implicit.Title,'');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_15,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import5.interpolate(1,'',this.context.$implicit.DateCreated,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_21,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import5.interpolate(2,'',this.context.$implicit.Sport,'/',this.context.$implicit.Skill,'');
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_29,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.context.$implicit.Duration,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_32,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.downloadMatrix()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage5(viewUtils,parentInjector,declarationEl);
}
var renderType_PopoverPage_Host:import0.RenderComponentType = (null as any);
class _View_PopoverPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PopoverPage_0_4:import4.PopoverPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_PopoverPage_Host0,renderType_PopoverPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PopoverPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PopoverPage_0_4 = new import4.PopoverPage(this.parentInjector.get(import33.ViewController),this.parentInjector.get(import14.AlertController));
    this._appEl_0.initComponent(this._PopoverPage_0_4,[],compView_0);
    compView_0.create(this._PopoverPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.PopoverPage) && (0 === requestNodeIndex))) { return this._PopoverPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_PopoverPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PopoverPage_Host === (null as any))) { (renderType_PopoverPage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_PopoverPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PopoverPageNgFactory:import16.ComponentFactory<import4.PopoverPage> = new import16.ComponentFactory<import4.PopoverPage>('ng-component',viewFactory_PopoverPage_Host0,import4.PopoverPage);
const styles_PopoverPage:any[] = [];
var renderType_PopoverPage:import0.RenderComponentType = (null as any);
class _View_PopoverPage0 extends import1.AppView<import4.PopoverPage> {
  _text_0:any;
  _el_1:any;
  _List_1_3:import54.List;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Item_3_4:import53.Item;
  _ItemContent_3_5:import53.ItemContent;
  _query_Label_3_0:import21.QueryList<any>;
  _query_Button_3_1:import21.QueryList<any>;
  _query_Icon_3_2:import21.QueryList<any>;
  _text_4:any;
  _el_5:any;
  _Icon_5_3:import23.Icon;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_PopoverPage0,renderType_PopoverPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_1,'no-lines','');
    this._List_1_3 = new import54.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import55.GestureController));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','item item-block');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import56.viewFactory_Item0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Item_3_4 = new import53.Item(this.parentInjector.get(import57.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_3),this.renderer);
    this._ItemContent_3_5 = new import53.ItemContent();
    this._query_Label_3_0 = new import21.QueryList<any>();
    this._query_Button_3_1 = new import21.QueryList<any>();
    this._query_Icon_3_2 = new import21.QueryList<any>();
    this._appEl_3.initComponent(this._Item_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_5,'item-left','');
    this.renderer.setElementAttribute(this._el_5,'name','information-circle');
    this.renderer.setElementAttribute(this._el_5,'role','img');
    this._Icon_5_3 = new import23.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText((null as any),'About\n      ',(null as any));
    this._query_Label_3_0.reset([]);
    this._Item_3_4.contentLabel = this._query_Label_3_0.first;
    compView_3.create(this._Item_3_4,[
      [].concat([this._el_5]),
      [],
      [].concat([
        this._text_4,
        this._text_6
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.Icon) && (5 === requestNodeIndex))) { return this._Icon_5_3; }
    if (((token === import53.Item) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_3_4; }
    if (((token === import53.ItemContent) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_3_5; }
    if (((token === import54.List) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._List_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'information-circle';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_5_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_3_1.dirty) {
        this._query_Button_3_1.reset([]);
        this._Item_3_4._buttons = this._query_Button_3_1;
        this._query_Button_3_1.notifyOnChanges();
      }
      if (this._query_Icon_3_2.dirty) {
        this._query_Icon_3_2.reset([this._Icon_5_3]);
        this._Item_3_4._icons = this._query_Icon_3_2;
        this._query_Icon_3_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_3_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Icon_5_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_5,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_5_3.ngOnDestroy();
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onAbout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PopoverPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.PopoverPage> {
  if ((renderType_PopoverPage === (null as any))) { (renderType_PopoverPage = viewUtils.createRenderComponentType('d:/git/sportspip/.tmp/pages/home/home.ts class PopoverPage - inline template',0,import15.ViewEncapsulation.None,styles_PopoverPage,{})); }
  return new _View_PopoverPage0(viewUtils,parentInjector,declarationEl);
}