import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import4 from './home';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import16 from '@angular/core/src/linker/component_factory';
export declare const HomePageNgFactory: import16.ComponentFactory<import4.HomePage>;
export declare function viewFactory_HomePage0(viewUtils: import5.ViewUtils, parentInjector: import6.Injector, declarationEl: import2.AppElement): import1.AppView<import4.HomePage>;
export declare const PopoverPageNgFactory: import16.ComponentFactory<import4.PopoverPage>;
export declare function viewFactory_PopoverPage0(viewUtils: import5.ViewUtils, parentInjector: import6.Injector, declarationEl: import2.AppElement): import1.AppView<import4.PopoverPage>;
