/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/nav/nav';
import * as import12 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import13 from 'ionic-angular/navigation/view-controller';
import * as import14 from 'ionic-angular/navigation/nav-controller-base';
import * as import15 from 'ionic-angular/components/app/app';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from 'ionic-angular/util/keyboard';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/zone/ng_zone';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from 'ionic-angular/gestures/gesture-controller';
import * as import22 from 'ionic-angular/transitions/transition-controller';
import * as import23 from 'ionic-angular/navigation/deep-linker';
var renderType_sportspip_Host:import0.RenderComponentType = (null as any);
class _View_sportspip_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _sportspip_0_4:import3.sportspip;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_sportspip_Host0,renderType_sportspip_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_sportspip0(this.viewUtils,this.injector(0),this._appEl_0);
    this._sportspip_0_4 = new import3.sportspip(this.parentInjector.get(import8.Platform));
    this._appEl_0.initComponent(this._sportspip_0_4,[],compView_0);
    compView_0.create(this._sportspip_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.sportspip) && (0 === requestNodeIndex))) { return this._sportspip_0_4; }
    return notFoundResult;
  }
}
function viewFactory_sportspip_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_sportspip_Host === (null as any))) { (renderType_sportspip_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_sportspip_Host0(viewUtils,parentInjector,declarationEl);
}
export const sportspipNgFactory:import10.ComponentFactory<import3.sportspip> = new import10.ComponentFactory<import3.sportspip>('ng-component',viewFactory_sportspip_Host0,import3.sportspip);
const styles_sportspip:any[] = [];
var renderType_sportspip:import0.RenderComponentType = (null as any);
class _View_sportspip0 extends import1.AppView<import3.sportspip> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _Nav_1_4:import11.Nav;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_sportspip0,renderType_sportspip,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import12.viewFactory_Nav0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Nav_1_4 = new import11.Nav(this.parentInjector.get(import13.ViewController,(null as any)),this.parentInjector.get(import14.NavControllerBase,(null as any)),this.parentInjector.get(import15.App),this.parentInjector.get(import16.Config),this.parentInjector.get(import17.Keyboard),new import18.ElementRef(this._el_1),this.parentInjector.get(import19.NgZone),this.renderer,this.parentInjector.get(import20.ComponentFactoryResolver),this.parentInjector.get(import21.GestureController),this.parentInjector.get(import22.TransitionController),this.parentInjector.get(import23.DeepLinker,(null as any)));
    this._appEl_1.initComponent(this._Nav_1_4,[],compView_1);
    compView_1.create(this._Nav_1_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.Nav) && (1 === requestNodeIndex))) { return this._Nav_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_1_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_1_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_sportspip0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.sportspip> {
  if ((renderType_sportspip === (null as any))) { (renderType_sportspip = viewUtils.createRenderComponentType('d:/git/sportspip/.tmp/app/app.html',0,import9.ViewEncapsulation.None,styles_sportspip,{})); }
  return new _View_sportspip0(viewUtils,parentInjector,declarationEl);
}