/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './editor';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/button/button';
import * as import19 from 'ionic-angular/components/icon/icon';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from 'ionic-angular/components/segment/segment';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from 'ionic-angular/components/content/content';
import * as import25 from 'ionic-angular/components/fab/fab';
import * as import26 from '@angular/common/src/directives/ng_if';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import37 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import42 from '@angular/forms/src/directives/ng_control';
import * as import43 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import44 from 'ionic-angular/components/grid/grid';
import * as import45 from 'ionic-angular/components/card/card';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from 'ionic-angular/components/item/item';
import * as import48 from 'ionic-angular/gestures/gesture-controller';
import * as import49 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import50 from 'ionic-angular/util/form';
var renderType_EditorPage_Host:import0.RenderComponentType = (null as any);
class _View_EditorPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _EditorPage_0_4:import3.EditorPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage_Host0,renderType_EditorPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-editor',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_EditorPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._EditorPage_0_4 = new import3.EditorPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.AlertController));
    this._appEl_0.initComponent(this._EditorPage_0_4,[],compView_0);
    compView_0.create(this._EditorPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.EditorPage) && (0 === requestNodeIndex))) { return this._EditorPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_EditorPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_EditorPage_Host === (null as any))) { (renderType_EditorPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_EditorPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const EditorPageNgFactory:import12.ComponentFactory<import3.EditorPage> = new import12.ComponentFactory<import3.EditorPage>('page-editor',viewFactory_EditorPage_Host0,import3.EditorPage);
const styles_EditorPage:any[] = [];
var renderType_EditorPage:import0.RenderComponentType = (null as any);
class _View_EditorPage0 extends import1.AppView<import3.EditorPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import14.Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import15.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _ToolbarItem_8_3:import16.ToolbarItem;
  _query_Button_8_0:import17.QueryList<any>;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Button_10_4:import18.Button;
  _el_11:any;
  _Icon_11_3:import19.Icon;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Button_13_4:import18.Button;
  _el_14:any;
  _Icon_14_3:import19.Icon;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Toolbar_18_4:import13.Toolbar;
  _text_19:any;
  _el_20:any;
  _NgModel_20_3:import20.NgModel;
  _NgControl_20_4:any;
  _NgControlStatus_20_5:import21.NgControlStatus;
  _Segment_20_6:import22.Segment;
  _query_SegmentButton_20_0:import17.QueryList<any>;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import23.NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Content_27_4:import24.Content;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _FabContainer_30_4:import25.FabContainer;
  _query_FabButton_30_0:import17.QueryList<any>;
  _query_FabList_30_1:import17.QueryList<any>;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _FabButton_32_4:import25.FabButton;
  _el_33:any;
  _Icon_33_3:import19.Icon;
  _text_34:any;
  _el_35:any;
  _FabList_35_3:import25.FabList;
  _query_FabButton_35_0:import17.QueryList<any>;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _FabButton_37_4:import25.FabButton;
  _el_38:any;
  _Icon_38_3:import19.Icon;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import2.AppElement;
  _FabButton_40_4:import25.FabButton;
  _el_41:any;
  _Icon_41_3:import19.Icon;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _FabButton_43_4:import25.FabButton;
  _el_44:any;
  _Icon_44_3:import19.Icon;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _FabButton_46_4:import25.FabButton;
  _el_47:any;
  _Icon_47_3:import19.Icon;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _FabButton_49_4:import25.FabButton;
  _el_50:any;
  _Icon_50_3:import19.Icon;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _anchor_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _TemplateRef_56_5:any;
  _NgIf_56_6:import26.NgIf;
  _text_57:any;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _TemplateRef_59_5:any;
  _NgIf_59_6:import26.NgIf;
  _text_60:any;
  _text_61:any;
  _anchor_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _TemplateRef_62_5:any;
  _NgIf_62_6:import26.NgIf;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  _Footer_65_3:import13.Footer;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import2.AppElement;
  _Toolbar_67_4:import13.Toolbar;
  _text_68:any;
  _text_69:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage0,renderType_EditorPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import30.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._el_5);
    var compView_5:any = import32.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import15.ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[[].concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_8,'end','');
    this._ToolbarItem_8_3 = new import16.ToolbarItem(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_8_0 = new import17.QueryList<any>();
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'icon-only','');
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this._appEl_10 = new import2.AppElement(10,8,this,this._el_10);
    var compView_10:any = import33.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import18.Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4,[],compView_10);
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','cloud-upload');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_11),this.renderer);
    compView_10.create(this._Button_10_4,[[].concat([this._el_11])],(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'icon-only','');
    this.renderer.setElementAttribute(this._el_13,'ion-button','');
    this._appEl_13 = new import2.AppElement(13,8,this,this._el_13);
    var compView_13:any = import33.viewFactory_Button0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Button_13_4 = new import18.Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_13),this.renderer);
    this._appEl_13.initComponent(this._Button_13_4,[],compView_13);
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'name','share');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this._Icon_14_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_14),this.renderer);
    compView_13.create(this._Button_13_4,[[].concat([this._el_14])],(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [],
      [],
      [].concat([this._el_8]),
      [].concat([
        this._text_4,
        this._el_5,
        this._text_7,
        this._text_16
      ]
      )
    ]
    ,(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_1,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','toolbar');
    this.renderer.setElementAttribute(this._el_18,'style','padding:0 60px 0 0;');
    this._appEl_18 = new import2.AppElement(18,1,this,this._el_18);
    var compView_18:any = import34.viewFactory_Toolbar0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Toolbar_18_4 = new import13.Toolbar(this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_18),this.renderer);
    this._appEl_18.initComponent(this._Toolbar_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_20_3 = new import20.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_20_4 = this._NgModel_20_3;
    this._NgControlStatus_20_5 = new import21.NgControlStatus(this._NgControl_20_4);
    this._Segment_20_6 = new import22.Segment(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_20),this.renderer,this._NgControl_20_4);
    this._query_SegmentButton_20_0 = new import17.QueryList<any>();
    this._text_21 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import35.TemplateRef_(this._appEl_22,viewFactory_EditorPage1);
    this._NgFor_22_6 = new import23.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_18.create(this._Toolbar_18_4,[
      [],
      [],
      [],
      [].concat([
        this._text_19,
        this._el_20,
        this._text_24
      ]
      )
    ]
    ,(null as any));
    this._text_25 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_27 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_27,'padding','true');
    this.renderer.setElementAttribute(this._el_27,'scroll','false');
    this.renderer.setElementAttribute(this._el_27,'style','background:#eee;');
    this._appEl_27 = new import2.AppElement(27,(null as any),this,this._el_27);
    var compView_27:any = import37.viewFactory_Content0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Content_27_4 = new import24.Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_27),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_27.initComponent(this._Content_27_4,[],compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_30,'edge','');
    this.renderer.setElementAttribute(this._el_30,'right','');
    this.renderer.setElementAttribute(this._el_30,'top','');
    this._appEl_30 = new import2.AppElement(30,27,this,this._el_30);
    var compView_30:any = import41.viewFactory_FabContainer0(this.viewUtils,this.injector(30),this._appEl_30);
    this._FabContainer_30_4 = new import25.FabContainer(new import28.ElementRef(this._el_30));
    this._query_FabButton_30_0 = new import17.QueryList<any>();
    this._query_FabList_30_1 = new import17.QueryList<any>();
    this._appEl_30.initComponent(this._FabContainer_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'ion-fab','');
    this.renderer.setElementAttribute(this._el_32,'mini','');
    this._appEl_32 = new import2.AppElement(32,30,this,this._el_32);
    var compView_32:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(32),this._appEl_32);
    this._FabButton_32_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_32),this.renderer);
    this._appEl_32.initComponent(this._FabButton_32_4,[],compView_32);
    this._el_33 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_33,'name','add');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_33),this.renderer);
    compView_32.create(this._FabButton_32_4,[[].concat([this._el_33])],(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-fab-list',(null as any));
    this._FabList_35_3 = new import25.FabList();
    this._query_FabButton_35_0 = new import17.QueryList<any>();
    this._text_36 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_37,'color','primary');
    this.renderer.setElementAttribute(this._el_37,'ion-fab','');
    this._appEl_37 = new import2.AppElement(37,35,this,this._el_37);
    var compView_37:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(37),this._appEl_37);
    this._FabButton_37_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_37),this.renderer);
    this._appEl_37.initComponent(this._FabButton_37_4,[],compView_37);
    this._el_38 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_38,'name','add');
    this.renderer.setElementAttribute(this._el_38,'role','img');
    this._Icon_38_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_38),this.renderer);
    compView_37.create(this._FabButton_37_4,[[].concat([this._el_38])],(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_40,'ion-fab','');
    this._appEl_40 = new import2.AppElement(40,35,this,this._el_40);
    var compView_40:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(40),this._appEl_40);
    this._FabButton_40_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_40),this.renderer);
    this._appEl_40.initComponent(this._FabButton_40_4,[],compView_40);
    this._el_41 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'name','easel');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_41),this.renderer);
    compView_40.create(this._FabButton_40_4,[[].concat([this._el_41])],(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'ion-fab','');
    this._appEl_43 = new import2.AppElement(43,35,this,this._el_43);
    var compView_43:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(43),this._appEl_43);
    this._FabButton_43_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_43),this.renderer);
    this._appEl_43.initComponent(this._FabButton_43_4,[],compView_43);
    this._el_44 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_44,'name','ios-film');
    this.renderer.setElementAttribute(this._el_44,'role','img');
    this._Icon_44_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_44),this.renderer);
    compView_43.create(this._FabButton_43_4,[[].concat([this._el_44])],(null as any));
    this._text_45 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_46,'ion-fab','');
    this._appEl_46 = new import2.AppElement(46,35,this,this._el_46);
    var compView_46:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(46),this._appEl_46);
    this._FabButton_46_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_46),this.renderer);
    this._appEl_46.initComponent(this._FabButton_46_4,[],compView_46);
    this._el_47 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','videocam');
    this.renderer.setElementAttribute(this._el_47,'role','img');
    this._Icon_47_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_47),this.renderer);
    compView_46.create(this._FabButton_46_4,[[].concat([this._el_47])],(null as any));
    this._text_48 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_49,'ion-fab','');
    this._appEl_49 = new import2.AppElement(49,35,this,this._el_49);
    var compView_49:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(49),this._appEl_49);
    this._FabButton_49_4 = new import25.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_49),this.renderer);
    this._appEl_49.initComponent(this._FabButton_49_4,[],compView_49);
    this._el_50 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_50,'name','log-in');
    this.renderer.setElementAttribute(this._el_50,'role','img');
    this._Icon_50_3 = new import19.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_50),this.renderer);
    compView_49.create(this._FabButton_49_4,[[].concat([this._el_50])],(null as any));
    this._text_51 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_FabButton_30_0.reset([
      this._FabButton_32_4,
      this._FabButton_37_4,
      this._FabButton_40_4,
      this._FabButton_43_4,
      this._FabButton_46_4,
      this._FabButton_49_4
    ]
    );
    this._FabContainer_30_4._mainButton = this._query_FabButton_30_0.first;
      compView_30.create(this._FabContainer_30_4,[[].concat([
        this._text_31,
        this._el_32,
        this._text_34,
        this._el_35,
        this._text_52
      ]
    )],(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_56 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_56 = new import2.AppElement(56,27,this,this._anchor_56);
    this._TemplateRef_56_5 = new import35.TemplateRef_(this._appEl_56,viewFactory_EditorPage2);
    this._NgIf_56_6 = new import26.NgIf(this._appEl_56.vcRef,this._TemplateRef_56_5);
    this._text_57 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_59 = new import2.AppElement(59,27,this,this._anchor_59);
    this._TemplateRef_59_5 = new import35.TemplateRef_(this._appEl_59,viewFactory_EditorPage3);
    this._NgIf_59_6 = new import26.NgIf(this._appEl_59.vcRef,this._TemplateRef_59_5);
    this._text_60 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_62 = new import2.AppElement(62,27,this,this._anchor_62);
    this._TemplateRef_62_5 = new import35.TemplateRef_(this._appEl_62,viewFactory_EditorPage4);
    this._NgIf_62_6 = new import26.NgIf(this._appEl_62.vcRef,this._TemplateRef_62_5);
    this._text_63 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_27.create(this._Content_27_4,[
      [].concat([this._el_30]),
      [].concat([
        this._text_28,
        this._text_29,
        this._text_53,
        this._text_54,
        this._text_55,
        this._appEl_56,
        this._text_57,
        this._text_58,
        this._appEl_59,
        this._text_60,
        this._text_61,
        this._appEl_62,
        this._text_63
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_64 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_65 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_65_3 = new import13.Footer(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_65),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_66 = this.renderer.createText(this._el_65,'\n  ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_65,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','toolbar');
    this._appEl_67 = new import2.AppElement(67,65,this,this._el_67);
    var compView_67:any = import34.viewFactory_Toolbar0(this.viewUtils,this.injector(67),this._appEl_67);
    this._Toolbar_67_4 = new import13.Toolbar(this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_67),this.renderer);
    this._appEl_67.initComponent(this._Toolbar_67_4,[],compView_67);
    this._text_68 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_67.create(this._Toolbar_67_4,[
      [],
      [],
      [],
      [].concat([this._text_68])
    ]
    ,(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_20,'ngModelChange',this.eventHandler(this._handle_ngModelChange_20_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_20_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_20_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_0.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_40,'click',this.eventHandler(this._handle_click_40_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_46,'click',this.eventHandler(this._handle_click_46_0.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_49,'click',this.eventHandler(this._handle_click_49_0.bind(this)));
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._anchor_56,
      this._text_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._anchor_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import19.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3; }
    if (((token === import18.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Button_10_4; }
    if (((token === import19.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3; }
    if (((token === import18.Button) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Button_13_4; }
    if (((token === import16.ToolbarItem) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ToolbarItem_8_3; }
    if (((token === import14.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Navbar_3_4; }
    if (((token === import35.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import23.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    if (((token === import20.NgModel) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgModel_20_3; }
    if (((token === import42.NgControl) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgControl_20_4; }
    if (((token === import21.NgControlStatus) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgControlStatus_20_5; }
    if (((token === import22.Segment) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Segment_20_6; }
    if (((token === import13.Toolbar) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Toolbar_18_4; }
    if (((token === import13.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Header_1_3; }
    if (((token === import19.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3; }
    if (((token === import25.FabButton) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._FabButton_32_4; }
    if (((token === import19.Icon) && (38 === requestNodeIndex))) { return this._Icon_38_3; }
    if (((token === import25.FabButton) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._FabButton_37_4; }
    if (((token === import19.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3; }
    if (((token === import25.FabButton) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._FabButton_40_4; }
    if (((token === import19.Icon) && (44 === requestNodeIndex))) { return this._Icon_44_3; }
    if (((token === import25.FabButton) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._FabButton_43_4; }
    if (((token === import19.Icon) && (47 === requestNodeIndex))) { return this._Icon_47_3; }
    if (((token === import25.FabButton) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._FabButton_46_4; }
    if (((token === import19.Icon) && (50 === requestNodeIndex))) { return this._Icon_50_3; }
    if (((token === import25.FabButton) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._FabButton_49_4; }
    if (((token === import25.FabList) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._FabList_35_3; }
    if (((token === import25.FabContainer) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._FabContainer_30_4; }
    if (((token === import35.TemplateRef) && (56 === requestNodeIndex))) { return this._TemplateRef_56_5; }
    if (((token === import26.NgIf) && (56 === requestNodeIndex))) { return this._NgIf_56_6; }
    if (((token === import35.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import26.NgIf) && (59 === requestNodeIndex))) { return this._NgIf_59_6; }
    if (((token === import35.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import26.NgIf) && (62 === requestNodeIndex))) { return this._NgIf_62_6; }
    if (((token === import24.Content) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Content_27_4; }
    if (((token === import13.Toolbar) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Toolbar_67_4; }
    if (((token === import13.Footer) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Footer_65_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = 'cloud-upload';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_11_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = 'share';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_14_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    changes = (null as any);
    const currVal_10:any = this.context.selectedViewIndex;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgModel_20_3.model = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgModel_20_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_17:any = this.context.views;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgFor_22_6.ngForOf = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_27_4.ngOnInit(); }
    const currVal_19:any = 'add';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Icon_33_3.name = currVal_19;
      this._expr_19 = currVal_19;
    }
    changed = false;
    const currVal_23:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._FabButton_37_4.color = currVal_23;
      changed = true;
      this._expr_23 = currVal_23;
    }
    if (changed) { this._appEl_37.componentView.markAsCheckOnce(); }
    const currVal_24:any = 'add';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._Icon_38_3.name = currVal_24;
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = 'easel';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._Icon_41_3.name = currVal_27;
      this._expr_27 = currVal_27;
    }
    const currVal_30:any = 'ios-film';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._Icon_44_3.name = currVal_30;
      this._expr_30 = currVal_30;
    }
    const currVal_33:any = 'videocam';
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._Icon_47_3.name = currVal_33;
      this._expr_33 = currVal_33;
    }
    const currVal_36:any = 'log-in';
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._Icon_50_3.name = currVal_36;
      this._expr_36 = currVal_36;
    }
    const currVal_38:any = this.context.ifViewOptions;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._NgIf_56_6.ngIf = currVal_38;
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this.context.ifViewCanvas;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._NgIf_59_6.ngIf = currVal_39;
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this.context.ifViewVideo;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._NgIf_62_6.ngIf = currVal_40;
      this._expr_40 = currVal_40;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_8_0.dirty) {
        this._query_Button_8_0.reset([
          this._Button_10_4,
          this._Button_13_4
        ]
        );
        this._ToolbarItem_8_3._buttons = this._query_Button_8_0;
        this._query_Button_8_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_20_0.dirty) {
          this._query_SegmentButton_20_0.reset([this._appEl_22.mapNestedViews(_View_EditorPage1,(nestedView:_View_EditorPage1):any => {
            return [nestedView._SegmentButton_0_4];
        })]);
        this._Segment_20_6._buttons = this._query_SegmentButton_20_0;
        this._query_SegmentButton_20_0.notifyOnChanges();
      }
      if (this._query_FabButton_35_0.dirty) {
        this._query_FabButton_35_0.reset([
          this._FabButton_37_4,
          this._FabButton_40_4,
          this._FabButton_43_4,
          this._FabButton_46_4,
          this._FabButton_49_4
        ]
        );
        this._FabList_35_3._setbuttons = this._query_FabButton_35_0;
        this._query_FabButton_35_0.notifyOnChanges();
      }
      if (this._query_FabList_30_1.dirty) {
        this._query_FabList_30_1.reset([this._FabList_35_3]);
        this._FabContainer_30_4._fabLists = this._query_FabList_30_1;
        this._query_FabList_30_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_13_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_30_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.firstParam,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_6,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_11_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_13,'disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_14_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Toolbar_18_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatus_20_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_20_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_20_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_20_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_20_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_20_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = this._Content_27_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_27,'statusbar-padding',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_20:any = this._Icon_33_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_33,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._FabList_35_3._visible;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_35,'fab-list-active',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_25:any = this._Icon_38_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_38,'hide',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = this._Icon_41_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_31:any = this._Icon_44_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_44,'hide',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_34:any = this._Icon_47_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_47,'hide',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_37:any = this._Icon_50_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_50,'hide',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_41:any = this._Toolbar_67_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_67,'statusbar-padding',currVal_41);
      this._expr_41 = currVal_41;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_20_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_11_3.ngOnDestroy();
    this._Icon_14_3.ngOnDestroy();
    this._NgModel_20_3.ngOnDestroy();
    this._Icon_33_3.ngOnDestroy();
    this._Icon_38_3.ngOnDestroy();
    this._Icon_41_3.ngOnDestroy();
    this._Icon_44_3.ngOnDestroy();
    this._Icon_47_3.ngOnDestroy();
    this._Icon_50_3.ngOnDestroy();
    this._FabContainer_30_4.ngOnDestroy();
    this._Content_27_4.ngOnDestroy();
  }
  private _handle_ngModelChange_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selectedViewIndex = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addView('blank')) !== false);
    return (true && pd_0);
  }
  private _handle_click_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addView('canvas')) !== false);
    return (true && pd_0);
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addView('video')) !== false);
    return (true && pd_0);
  }
  private _handle_click_46_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addView('camera')) !== false);
    return (true && pd_0);
  }
  private _handle_click_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addView('library')) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_EditorPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.EditorPage> {
  if ((renderType_EditorPage === (null as any))) { (renderType_EditorPage = viewUtils.createRenderComponentType('d:/git/sportspip/.tmp/pages/editor/editor.html',0,import11.ViewEncapsulation.None,styles_EditorPage,{})); }
  return new _View_EditorPage0(viewUtils,parentInjector,declarationEl);
}
class _View_EditorPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SegmentButton_0_4:import22.SegmentButton;
  _text_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage1,renderType_EditorPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','segment-button');
    this.renderer.setElementAttribute(this._el_0,'role','button');
    this.renderer.setElementAttribute(this._el_0,'tappable','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import43.viewFactory_SegmentButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SegmentButton_0_4 = new import22.SegmentButton(this.renderer,new import28.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._SegmentButton_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    compView_0.create(this._SegmentButton_0_4,[[].concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'press',this.eventHandler(this._handle_press_0_1.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.SegmentButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._SegmentButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._SegmentButton_0_4.value = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = import4.interpolate(1,'\n        ',('View ' + (this.context.index + 1)),'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_EditorPage0>this.parent)._query_SegmentButton_20_0.setDirty();
  }
  private _handle_click_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.showSegment(this.context.index)) !== false);
    const pd_1:any = ((<any>this._SegmentButton_0_4.onClick()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_press_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.deleteView(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_EditorPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_EditorPage1(viewUtils,parentInjector,declarationEl);
}
class _View_EditorPage2 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import44.Row;
  _text_1:any;
  _el_2:any;
  _Col_2_3:import44.Col;
  _text_3:any;
  _el_4:any;
  _Card_4_3:import45.Card;
  _text_5:any;
  _el_6:any;
  _CardHeader_6_3:import45.CardHeader;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _List_9_3:import46.List;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Item_11_4:import47.Item;
  _ItemContent_11_5:import47.ItemContent;
  _query_Label_11_0:import17.QueryList<any>;
  _query_Button_11_1:import17.QueryList<any>;
  _query_Icon_11_2:import17.QueryList<any>;
  _el_12:any;
  _Icon_12_3:import19.Icon;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Item_15_4:import47.Item;
  _ItemContent_15_5:import47.ItemContent;
  _query_Label_15_0:import17.QueryList<any>;
  _query_Button_15_1:import17.QueryList<any>;
  _query_Icon_15_2:import17.QueryList<any>;
  _el_16:any;
  _Icon_16_3:import19.Icon;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _Item_19_4:import47.Item;
  _ItemContent_19_5:import47.ItemContent;
  _query_Label_19_0:import17.QueryList<any>;
  _query_Button_19_1:import17.QueryList<any>;
  _query_Icon_19_2:import17.QueryList<any>;
  _el_20:any;
  _Icon_20_3:import19.Icon;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import47.Item;
  _ItemContent_23_5:import47.ItemContent;
  _query_Label_23_0:import17.QueryList<any>;
  _query_Button_23_1:import17.QueryList<any>;
  _query_Icon_23_2:import17.QueryList<any>;
  _el_24:any;
  _Icon_24_3:import19.Icon;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage2,renderType_EditorPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','height:100%;');
    this._Row_0_3 = new import44.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_2,'center','');
    this.renderer.setElementAttribute(this._el_2,'text-center','');
    this._Col_2_3 = new import44.Col();
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','width:250px;');
    this._Card_4_3 = new import45.Card(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-card-header',(null as any));
    this._CardHeader_6_3 = new import45.CardHeader();
    this._text_7 = this.renderer.createText(this._el_6,'Choose view type..',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'ion-list',(null as any));
    this._List_9_3 = new import46.List(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parent.parentInjector.get(import48.GestureController));
    this._text_10 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','item item-block');
    this.renderer.setElementAttribute(this._el_11,'ion-item','');
    this._appEl_11 = new import2.AppElement(11,9,this,this._el_11);
    var compView_11:any = import49.viewFactory_Item0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Item_11_4 = new import47.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_11),this.renderer);
    this._ItemContent_11_5 = new import47.ItemContent();
    this._query_Label_11_0 = new import17.QueryList<any>();
    this._query_Button_11_1 = new import17.QueryList<any>();
    this._query_Icon_11_2 = new import17.QueryList<any>();
    this._appEl_11.initComponent(this._Item_11_4,[],compView_11);
    this._el_12 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_12,'item-left','');
    this.renderer.setElementAttribute(this._el_12,'name','easel');
    this.renderer.setElementAttribute(this._el_12,'role','img');
    this._Icon_12_3 = new import19.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText((null as any),'Blank Canvas',(null as any));
    this._query_Label_11_0.reset([]);
    this._Item_11_4.contentLabel = this._query_Label_11_0.first;
    compView_11.create(this._Item_11_4,[
      [].concat([this._el_12]),
      [],
      [].concat([this._text_13]),
      [],
      []
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_9,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this.renderer.setElementAttribute(this._el_15,'ion-item','');
    this._appEl_15 = new import2.AppElement(15,9,this,this._el_15);
    var compView_15:any = import49.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import47.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import47.ItemContent();
    this._query_Label_15_0 = new import17.QueryList<any>();
    this._query_Button_15_1 = new import17.QueryList<any>();
    this._query_Icon_15_2 = new import17.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4,[],compView_15);
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'item-left','');
    this.renderer.setElementAttribute(this._el_16,'name','ios-film');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import19.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText((null as any),'Add Video',(null as any));
    this._query_Label_15_0.reset([]);
    this._Item_15_4.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4,[
      [].concat([this._el_16]),
      [],
      [].concat([this._text_17]),
      [],
      []
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_9,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item item-block');
    this.renderer.setElementAttribute(this._el_19,'ion-item','');
    this._appEl_19 = new import2.AppElement(19,9,this,this._el_19);
    var compView_19:any = import49.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import47.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_19),this.renderer);
    this._ItemContent_19_5 = new import47.ItemContent();
    this._query_Label_19_0 = new import17.QueryList<any>();
    this._query_Button_19_1 = new import17.QueryList<any>();
    this._query_Icon_19_2 = new import17.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4,[],compView_19);
    this._el_20 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'item-left','');
    this.renderer.setElementAttribute(this._el_20,'name','videocam');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import19.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'Record Video',(null as any));
    this._query_Label_19_0.reset([]);
    this._Item_19_4.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4,[
      [].concat([this._el_20]),
      [],
      [].concat([this._text_21]),
      [],
      []
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_9,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this.renderer.setElementAttribute(this._el_23,'ion-item','');
    this._appEl_23 = new import2.AppElement(23,9,this,this._el_23);
    var compView_23:any = import49.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import47.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import47.ItemContent();
    this._query_Label_23_0 = new import17.QueryList<any>();
    this._query_Button_23_1 = new import17.QueryList<any>();
    this._query_Icon_23_2 = new import17.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._el_24 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_24,'item-left','');
    this.renderer.setElementAttribute(this._el_24,'name','log-in');
    this.renderer.setElementAttribute(this._el_24,'role','img');
    this._Icon_24_3 = new import19.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText((null as any),'Import from library',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [].concat([this._el_24]),
      [],
      [].concat([this._text_25]),
      [],
      []
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.CardHeader) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._CardHeader_6_3; }
    if (((token === import19.Icon) && (12 === requestNodeIndex))) { return this._Icon_12_3; }
    if (((token === import47.Item) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_11_4; }
    if (((token === import47.ItemContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_11_5; }
    if (((token === import19.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3; }
    if (((token === import47.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_15_4; }
    if (((token === import47.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemContent_15_5; }
    if (((token === import19.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import47.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_19_4; }
    if (((token === import47.ItemContent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_19_5; }
    if (((token === import19.Icon) && (24 === requestNodeIndex))) { return this._Icon_24_3; }
    if (((token === import47.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_23_4; }
    if (((token === import47.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ItemContent_23_5; }
    if (((token === import46.List) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._List_9_3; }
    if (((token === import45.Card) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Card_4_3; }
    if (((token === import44.Col) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Col_2_3; }
    if (((token === import44.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'easel';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_12_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = 'ios-film';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_16_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = 'videocam';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_20_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = 'log-in';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_24_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_11_1.dirty) {
        this._query_Button_11_1.reset([]);
        this._Item_11_4._buttons = this._query_Button_11_1;
        this._query_Button_11_1.notifyOnChanges();
      }
      if (this._query_Icon_11_2.dirty) {
        this._query_Icon_11_2.reset([this._Icon_12_3]);
        this._Item_11_4._icons = this._query_Icon_11_2;
        this._query_Icon_11_2.notifyOnChanges();
      }
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset([]);
        this._Item_15_4._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset([this._Icon_16_3]);
        this._Item_15_4._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset([]);
        this._Item_19_4._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset([this._Icon_20_3]);
        this._Item_19_4._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_24_3]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_11_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_15_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_19_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Icon_12_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_12,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._Icon_16_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_20_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_24_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_24,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_12_3.ngOnDestroy();
    this._Icon_16_3.ngOnDestroy();
    this._Icon_20_3.ngOnDestroy();
    this._Icon_24_3.ngOnDestroy();
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.defineView('canvas')) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.defineView('video')) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.defineView('camera')) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.importFromLibrary()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_EditorPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_EditorPage2(viewUtils,parentInjector,declarationEl);
}
class _View_EditorPage3 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import44.Row;
  _text_1:any;
  _el_2:any;
  _Col_2_3:import44.Col;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage3,renderType_EditorPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','height: 100%;background:#fff;');
    this._Row_0_3 = new import44.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','flex: 0 0 50%;max-width: 50%;text-align: center;');
    this._Col_2_3 = new import44.Col();
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Col) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Col_2_3; }
    if (((token === import44.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n      ',this.parent.context.selectedView.type,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_EditorPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_EditorPage3(viewUtils,parentInjector,declarationEl);
}
class _View_EditorPage4 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import44.Row;
  _text_1:any;
  _el_2:any;
  _Col_2_3:import44.Col;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_EditorPage4,renderType_EditorPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','height: 100%;background:#444;');
    this._Row_0_3 = new import44.Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','flex: 0 0 50%;max-width: 50%;text-align: center;');
    this._Col_2_3 = new import44.Col();
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Col) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Col_2_3; }
    if (((token === import44.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Row_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n      ',this.parent.context.selectedView.type,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_EditorPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_EditorPage4(viewUtils,parentInjector,declarationEl);
}